apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "workload-resource-controller.fullname" . }}-cm
data:
  workload-resource-controller-cm.yaml: |
{{ .Values.controllerConfig | indent 4 }}